services:
  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"
    environment:
      - DB_FILE_NAME=file:/app/data/simple_sqlite_db.db
    volumes:
      - sqlite_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"

volumes:
  sqlite_data:
